"""initial

Revision ID: 398487ce2907
Revises: 
Create Date: 2026-09-10 05:14:10.355781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '398487ce2907'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS citext')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Enum('user', 'client', 'system', name='audit_actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('fingerprint_hash', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('kk', 'ru', 'en', name='language'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('default_language', sa.Enum('kk', 'ru', 'en', name='language'), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('brand_color', sa.Text(), nullable=True),
    sa.Column('plan', sa.Enum('trial', 'basic', 'pro', name='plan'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('one_ticket_per_org', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('push_subscriptions',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_table('queues',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ticket_prefix', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'paused', 'closed', name='queue_status'), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('geo_radius_m', sa.Integer(), nullable=True),
    sa.Column('presence_timeout_min', sa.Integer(), nullable=False),
    sa.Column('daily_ticket_limit', sa.Integer(), nullable=True),
    sa.Column('last_ticket_number', sa.Integer(), nullable=False),
    sa.Column('counter_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('superadmin', 'org_admin', 'operator', 'registrar', name='user_role'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('totp_secret', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cabinets',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('queue_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('free', 'busy', 'paused', 'offline', name='cabinet_status'), nullable=False),
    sa.Column('current_ticket_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['current_ticket_id'], ['tickets.id'], name='fk_cabinets_current_ticket_id', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_schedules',
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=False),
    sa.Column('closes_at', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_screens',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('queue_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('pairing_code', sa.Text(), nullable=True),
    sa.Column('device_token', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('kk', 'ru', 'en', name='language'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cabinet_operators',
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('cabinet_id', 'user_id')
    )
    op.create_table('tickets',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('display_number', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'called', 'confirmed', 'serving', 'served', 'no_show', 'left', 'transferred', name='ticket_status'), nullable=False),
    sa.Column('source', sa.Enum('qr', 'registrar', 'transfer', name='ticket_source'), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=True),
    sa.Column('called_by', sa.UUID(), nullable=True),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('transferred_from', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('serving_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('rating_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.ForeignKeyConstraint(['called_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.ForeignKeyConstraint(['transferred_from'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tickets_org_created', 'tickets', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_tickets_queue_status_created', 'tickets', ['queue_id', 'status', 'created_at'], unique=False)
    op.create_index('ux_tickets_active_per_client_queue', 'tickets', ['client_id', 'queue_id'], unique=True, postgresql_where=sa.text("status IN ('waiting', 'called', 'confirmed', 'serving')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_tickets_active_per_client_queue', table_name='tickets', postgresql_where=sa.text("status IN ('waiting', 'called', 'confirmed', 'serving')"))
    op.drop_index('ix_tickets_queue_status_created', table_name='tickets')
    op.drop_index('ix_tickets_org_created', table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('cabinet_operators')
    op.drop_table('tv_screens')
    op.drop_table('queue_schedules')
    op.drop_table('cabinets')
    op.drop_table('users')
    op.drop_table('queues')
    op.drop_table('push_subscriptions')
    op.drop_table('organizations')
    op.drop_table('clients')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
