"""add tickets position_notified

Revision ID: 78180560d744
Revises: bfb0ead12d4a
Create Date: 2026-09-10 19:40:52.695113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78180560d744'
down_revision: Union[str, None] = 'bfb0ead12d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows so the NOT NULL add doesn't
    # fail against a non-empty table; dropped right after so the model's
    # own Python-side default (not a DB default) is what governs new rows.
    op.add_column(
        'tickets',
        sa.Column('position_notified', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('tickets', 'position_notified', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'position_notified')
    # ### end Alembic commands ###
