"""queue manually_paused flag

Revision ID: 9fe4fe679793
Revises: 78180560d744
Create Date: 2026-09-11 03:24:22.540268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe4fe679793'
down_revision: Union[str, None] = '78180560d744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'queues',
        sa.Column('manually_paused', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('queues', 'manually_paused', server_default=None)
    op.execute("UPDATE queues SET manually_paused = true WHERE status = 'paused'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'manually_paused')
    # ### end Alembic commands ###
