"""fix_cabinets_current_ticket_fk

Revision ID: bfb0ead12d4a
Revises: 398487ce2907
Create Date: 2026-09-10 06:38:01.312159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb0ead12d4a'
down_revision: Union[str, None] = '398487ce2907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_cabinets_current_ticket_id', 'cabinets', 'tickets', ['current_ticket_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cabinets_current_ticket_id', 'cabinets', type_='foreignkey')
    # ### end Alembic commands ###
